// <auto-generated />
namespace Capstone5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Weeklyspecialstospecials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Weeklyspecialstospecials));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241736593_Weekly specials to specials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
